"""Shared reason-code literals for the candidate funnel.

These values are CSV/JSON-facing contracts. Keep the emitted strings exactly
stable unless there is an explicit artifact migration.
"""

# Runtime ineligibility reasons returned by gate helpers.
GAME_STATUS_REASON_FINAL = "game_final"
GAME_STATUS_REASON_IN_PROGRESS = "game_in_progress"
GAME_STATUS_REASON_POSTPONED = "game_postponed"
GAME_STATUS_REASON_LOCKED = "game_locked"
GAME_STATUS_REASON_UNKNOWN = "game_status_unknown"
ODDS_STALE_REASON = "odds_stale"

# Elite admission and telemetry reasons.
REJECT_INJURY_FLAG = "reject_injury_flag"
REJECT_MINUTES_VOLATILITY = "reject_minutes_volatility"
REJECT_CONFIDENCE_BELOW_THRESHOLD = "reject_confidence_below_threshold"
REJECT_PROJECTION_REALISM = "reject_projection_realism"
REJECT_EXPOSURE_LIMIT = "reject_exposure_limit"
REJECT_NEGATIVE_EDGE_DIRECTION = "reject_negative_edge_direction"
REJECT_UNREALISTIC_LINE = "reject_unrealistic_line"
REJECT_HEAVY_FAVORITE_ODDS = "reject_heavy_favorite_odds"
REJECT_OTHER = "reject_other"
ELITE_REJECT_CONTEXT_HIGH_CAUTION_OVER = "elite_reject_context_high_caution_over"
ELITE_REJECT_GAME_CONTEXT_SUPPRESSED = "elite_reject_game_context_suppressed"
ELITE_REJECT_PLAYER_POINTS_STRONG_OVER_CALIBRATION = (
    "elite_reject_player_points_strong_over_calibration"
)
ELITE_REJECT_GAME_NOT_BETTABLE = "elite_reject_game_not_bettable"
ELITE_REJECT_GAME_FINAL = "elite_reject_game_final"
ELITE_REJECT_GAME_IN_PROGRESS = "elite_reject_game_in_progress"
ELITE_REJECT_GAME_LOCKED = "elite_reject_game_locked"
ELITE_REJECT_GAME_POSTPONED = "elite_reject_game_postponed"
ELITE_REJECT_ODDS_STALE = "elite_reject_odds_stale"

# Kelly skip reasons.
KELLY_PROJECTED_SKIP_CONTEXT_HIGH_CAUTION_OVER = "context_high_caution_over"
KELLY_PROJECTED_SKIP_PLAYER_POINTS_STRONG_OVER_CALIBRATION = (
    "player_points_strong_over_calibration"
)
KELLY_SKIP_CONTEXT_HIGH_CAUTION_OVER = KELLY_PROJECTED_SKIP_CONTEXT_HIGH_CAUTION_OVER
KELLY_SKIP_GAME_NOT_BETTABLE = "game_not_bettable"
KELLY_SKIP_GAME_FINAL = GAME_STATUS_REASON_FINAL
KELLY_SKIP_GAME_IN_PROGRESS = GAME_STATUS_REASON_IN_PROGRESS
KELLY_SKIP_GAME_LOCKED = GAME_STATUS_REASON_LOCKED
KELLY_SKIP_GAME_POSTPONED = GAME_STATUS_REASON_POSTPONED
KELLY_SKIP_ODDS_STALE = ODDS_STALE_REASON
KELLY_SKIP_POINTS_ONLY_MARKET_LOCK = "kelly_points_only_market_lock"
KELLY_SKIP_MISSING_OR_INVALID_ODDS = "missing_or_invalid_odds"
KELLY_SKIP_NON_POSITIVE_DECIMAL_ODDS = "non_positive_decimal_odds"
KELLY_SKIP_MISSING_CONFIDENCE = "missing_confidence"
KELLY_SKIP_NON_POSITIVE_EDGE = "non_positive_edge"
KELLY_SKIP_RETURNED_ZERO = "kelly_returned_zero"
EDGE_CONTAINMENT_HOLD_SKIP_REASON = "edge_containment_hold_for_review"
MEDIUM_NEUTRAL_OVER_DAMPENER_REASON = "medium_neutral_over_dampener"

# Selection/operator-board reasons.
UNSUPPORTED_ACTIVE_OPERATOR_MARKET_REASON = "unsupported_active_operator_market"
DUPLICATE_BETTING_IDENTITY_REASON = "duplicate_betting_identity"
UNSUPPORTED_MILESTONE_MARKET_REASON = "unsupported_milestone_market"
SELECTION_NOT_LIVE_MARKET_ELIGIBLE_REASON = "selection_not_live_market_eligible"
SELECTION_LIVE_GATE_MISSING_QUALIFICATION_REASON = (
    "selection_live_gate_missing_qualification_reason"
)
SELECTION_LIVE_GATE_FILTERED_REASON = "selection_live_gate_filtered"
SELECTION_NOT_SELECTED_BY_BOARD_SELECTOR_REASON = (
    "selection_not_selected_by_board_selector"
)

# Runtime selection guard reasons.
PLAYER_POINTS_STRONG_OVER_CALIBRATION_GUARD_REASON = (
    "player_points_strong_over_calibration_guard"
)

# Telemetry counters.
PASSED_TO_ELITE = "passed_to_elite"
TOTAL_CANDIDATES = "total_candidates"


__all__ = [
    "DUPLICATE_BETTING_IDENTITY_REASON",
    "EDGE_CONTAINMENT_HOLD_SKIP_REASON",
    "ELITE_REJECT_CONTEXT_HIGH_CAUTION_OVER",
    "ELITE_REJECT_GAME_CONTEXT_SUPPRESSED",
    "ELITE_REJECT_GAME_FINAL",
    "ELITE_REJECT_GAME_IN_PROGRESS",
    "ELITE_REJECT_GAME_LOCKED",
    "ELITE_REJECT_GAME_NOT_BETTABLE",
    "ELITE_REJECT_GAME_POSTPONED",
    "ELITE_REJECT_ODDS_STALE",
    "ELITE_REJECT_PLAYER_POINTS_STRONG_OVER_CALIBRATION",
    "GAME_STATUS_REASON_FINAL",
    "GAME_STATUS_REASON_IN_PROGRESS",
    "GAME_STATUS_REASON_LOCKED",
    "GAME_STATUS_REASON_POSTPONED",
    "GAME_STATUS_REASON_UNKNOWN",
    "KELLY_PROJECTED_SKIP_CONTEXT_HIGH_CAUTION_OVER",
    "KELLY_PROJECTED_SKIP_PLAYER_POINTS_STRONG_OVER_CALIBRATION",
    "KELLY_SKIP_CONTEXT_HIGH_CAUTION_OVER",
    "KELLY_SKIP_GAME_FINAL",
    "KELLY_SKIP_GAME_IN_PROGRESS",
    "KELLY_SKIP_GAME_LOCKED",
    "KELLY_SKIP_GAME_NOT_BETTABLE",
    "KELLY_SKIP_GAME_POSTPONED",
    "KELLY_SKIP_MISSING_CONFIDENCE",
    "KELLY_SKIP_MISSING_OR_INVALID_ODDS",
    "KELLY_SKIP_NON_POSITIVE_DECIMAL_ODDS",
    "KELLY_SKIP_NON_POSITIVE_EDGE",
    "KELLY_SKIP_ODDS_STALE",
    "KELLY_SKIP_POINTS_ONLY_MARKET_LOCK",
    "KELLY_SKIP_RETURNED_ZERO",
    "MEDIUM_NEUTRAL_OVER_DAMPENER_REASON",
    "ODDS_STALE_REASON",
    "PASSED_TO_ELITE",
    "PLAYER_POINTS_STRONG_OVER_CALIBRATION_GUARD_REASON",
    "REJECT_CONFIDENCE_BELOW_THRESHOLD",
    "REJECT_EXPOSURE_LIMIT",
    "REJECT_HEAVY_FAVORITE_ODDS",
    "REJECT_INJURY_FLAG",
    "REJECT_MINUTES_VOLATILITY",
    "REJECT_NEGATIVE_EDGE_DIRECTION",
    "REJECT_OTHER",
    "REJECT_PROJECTION_REALISM",
    "REJECT_UNREALISTIC_LINE",
    "SELECTION_LIVE_GATE_FILTERED_REASON",
    "SELECTION_LIVE_GATE_MISSING_QUALIFICATION_REASON",
    "SELECTION_NOT_LIVE_MARKET_ELIGIBLE_REASON",
    "SELECTION_NOT_SELECTED_BY_BOARD_SELECTOR_REASON",
    "TOTAL_CANDIDATES",
    "UNSUPPORTED_ACTIVE_OPERATOR_MARKET_REASON",
    "UNSUPPORTED_MILESTONE_MARKET_REASON",
]
