"""Context-layer helpers for passive operator diagnostics."""

from .manual_player_context import (
    MANUAL_CONTEXT_COLUMNS,
    MANUAL_CONTEXT_OUTPUT_COLUMNS,
    apply_manual_player_context,
    load_manual_player_context,
    write_manual_context_diagnostics,
)
from .game_context import (
    GAME_CONTEXT_COLUMNS,
    IDENTITY_QUARANTINE_ACTION,
    IDENTITY_QUARANTINE_REJECTION_REASON,
    apply_game_context,
    format_identity_quarantine_line,
    identity_quarantine_reason_counts,
    identity_quarantine_summary,
    is_identity_quarantined,
    mark_identity_quarantine_fields,
    write_game_context_outputs,
)
from .player_identity import (
    BASELINE_PROVIDER_TEAM_CONFLICT_REASON,
    PLAYER_ID_TEAM_CONFLICT_REASON,
    PLAYER_IDENTITY_REJECTION_REASON,
    PLAYER_TEAM_NOT_IN_ACTIVE_GAME_REASON,
    SOURCE_IDENTITY_CONFLICT_COLUMNS,
    SOURCE_IDENTITY_CONFLICT_POLICY_ROW_VALID,
    annotate_source_identity_conflicts,
    build_canonical_player_identity_resolver,
    player_identity_reason_counts,
    source_identity_conflict_exposure_summary,
    source_identity_conflicted_row_count,
)
from .game_strength import (
    POWER_RATING_CONTEXT_COLUMNS,
    apply_power_rating_context_to_df,
    get_matchup_context,
    get_matchup_context_batch,
)

__all__ = [
    "MANUAL_CONTEXT_COLUMNS",
    "MANUAL_CONTEXT_OUTPUT_COLUMNS",
    "GAME_CONTEXT_COLUMNS",
    "IDENTITY_QUARANTINE_ACTION",
    "IDENTITY_QUARANTINE_REJECTION_REASON",
    "POWER_RATING_CONTEXT_COLUMNS",
    "apply_manual_player_context",
    "apply_game_context",
    "format_identity_quarantine_line",
    "identity_quarantine_reason_counts",
    "identity_quarantine_summary",
    "is_identity_quarantined",
    "mark_identity_quarantine_fields",
    "apply_power_rating_context_to_df",
    "get_matchup_context",
    "get_matchup_context_batch",
    "load_manual_player_context",
    "write_manual_context_diagnostics",
    "write_game_context_outputs",
    "BASELINE_PROVIDER_TEAM_CONFLICT_REASON",
    "PLAYER_ID_TEAM_CONFLICT_REASON",
    "PLAYER_IDENTITY_REJECTION_REASON",
    "PLAYER_TEAM_NOT_IN_ACTIVE_GAME_REASON",
    "SOURCE_IDENTITY_CONFLICT_COLUMNS",
    "SOURCE_IDENTITY_CONFLICT_POLICY_ROW_VALID",
    "annotate_source_identity_conflicts",
    "build_canonical_player_identity_resolver",
    "player_identity_reason_counts",
    "source_identity_conflict_exposure_summary",
    "source_identity_conflicted_row_count",
]
